# -*- coding: utf-8 -*-
"""Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOs4AretMjyOePFyHuv8DBckrbBUsgDK

# Model Training using IoT Data

Import Libraries
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import joblib
import numpy as np

"""Load Data"""

data = pd.read_csv('/content/drive/MyDrive/iot_telemetry_data.csv')

"""Data Preparetion"""

data['light'] = data['light'].astype(int)
data['motion'] = data['motion'].astype(int)

"""Train-Test Split"""

X = data[['co', 'humidity', 'light', 'lpg', 'motion', 'smoke']]
y = data['temp']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Model Loading

model = XGBRegressor(objective='reg:squarederror', random_state=42)
model.fit(X_train, y_train)


joblib.dump(model, 'xgboost_regression_model.joblib')
joblib.dump(scaler, 'scaler.joblib')


y_pred = model.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')


plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, alpha=0.7, color='b')
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2)
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title('Actual vs Predicted Values')
plt.show()


def predict_temperature(user_input):
    model = joblib.load('xgboost_regression_model.joblib')
    scaler = joblib.load('scaler.joblib')


    user_input = np.array(user_input).reshape(1, -1)
    user_input_scaled = scaler.transform(user_input)


    predicted_temp = model.predict(user_input_scaled)
    return predicted_temp[0]


user_input = [0.004, 55.0, 1, 0.006, 0, 0.018]

predicted_temp = predict_temperature(user_input)
print(f'Predicted Temperature: {predicted_temp}')